spring.security.oauth2.client.registration.goole.client-id=852673051256-6gmdkrjppgs1ivq0nrvdsedf26tfoitl.apps.googleusercontent.com
spring.security.oauth2.client.registration.goole.client-secret=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
spring.security.oauth2.client.registration.goole.scope=profile,email